# Learn numpy Library

In [1]:
import numpy as np

In [2]:
# Normal array
a = [1,23,4,5,6,7,8,9,10]

In [3]:
a

[1, 23, 4, 5, 6, 7, 8, 9, 10]

In [4]:
type(a)

list

# numpy array

In [5]:
l = np.array([1, 23, 4, 5, 6, 7, 8, 9, 10])

In [7]:
l

array([ 1, 23,  4,  5,  6,  7,  8,  9, 10])

In [8]:
type(l)

numpy.ndarray

In [9]:
l.dtype

dtype('int64')

In [10]:
l = np.array([1, 23, 4, 5, 6, 7, 8, 9, 10], dtype=float)

In [11]:
l

array([ 1., 23.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [12]:
l = np.array([1, 23, 4, 5, 6, 7, 8, 9, 10], dtype=int)

In [13]:
l

array([ 1, 23,  4,  5,  6,  7,  8,  9, 10])

In [14]:
np.random.rand(10)

array([0.50238475, 0.06265936, 0.68018507, 0.17674447, 0.20194353,
       0.98745902, 0.63206385, 0.0094735 , 0.07839901, 0.51292427])

In [16]:
np.random.random(50)

array([0.23964411, 0.91051929, 0.55959823, 0.45014099, 0.35238119,
       0.37600904, 0.76239447, 0.7723743 , 0.50229185, 0.80452314,
       0.85766766, 0.90808614, 0.94098526, 0.08632038, 0.54801874,
       0.00356481, 0.74490477, 0.13241759, 0.07274343, 0.94257888,
       0.88738316, 0.50562138, 0.65997583, 0.82620332, 0.39108409,
       0.24595327, 0.79149514, 0.22957498, 0.88227075, 0.08197498,
       0.39202088, 0.60068607, 0.48070512, 0.80710691, 0.10405123,
       0.25250582, 0.01373946, 0.67221602, 0.37287675, 0.30185525,
       0.3485837 , 0.71184926, 0.46122209, 0.72473874, 0.38901225,
       0.32623926, 0.41820701, 0.84095115, 0.5700847 , 0.21386298])

In [17]:
np.random.randint(50,100, 20)

array([61, 90, 71, 68, 73, 52, 55, 63, 68, 78, 87, 57, 82, 73, 93, 85, 98,
       66, 72, 56])

In [18]:
heights = np.array([4.5,6,55])
weights = np.array([65,52,70])

bmi = weights / (heights**2)
print(bmi)

[3.20987654 1.44444444 0.0231405 ]


In [22]:
ages =np.array([[[10,23,65,50]]])

In [25]:
ages.shape

(1, 1, 4)

In [ ]:
# find 65
ages[0][0][2]
# print(ages[0][0][2])

65
